download: false
preprocess: false
hparam_search: false
pretrain: true
train: true
eval: true

all_folds: false
all_folds_workers: 1

load_checkpoint: false
checkpoint_path: "checkpoints/pretrain/long-pretrain+znormalize/best_pretrained_epoch_4.pth"
