download: false
preprocess: false
hparam_search: true
pretrain: false
train: false
eval: false

all_folds: false
all_folds_workers: 1

load_checkpoint: true
checkpoint_path: "checkpoints/pretrain/allfolds_100hz/best_pretrained_epoch_9.pth"
